apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oppam-uploads-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
