apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backfill-nightly
  namespace: trading
  labels:
    app: data-backfill
    app.kubernetes.io/part-of: algo-trading-system
spec:
  schedule: "0 6 * * *" # 1:00 AM EST (Winter) / 2:00 AM EDT (Summer)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backfill
            image: docker.io/sudhan03/algo-trading:data-ingestion-latest
            imagePullPolicy: Always
            command: ["python", "/app/scripts/deep_backfill.py", "--days", "2"]
            env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: ALPACA_API_KEY
            - name: ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: ALPACA_SECRET_KEY
            - name: DB_HOST
              value: "timescaledb"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "trading_db"
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                    name: trading-secrets
                    key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: trading-secrets
                    key: DB_PASSWORD
            resources:
              requests:
                memory: "4Gi"
                cpu: "2000m"
              limits:
                memory: "32Gi"
                cpu: "8000m"
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-hub-creds
