apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-regime-retrainer
  namespace: trading
spec:
  schedule: "0 2 * * 0" # Weekly on Sunday at 02:00
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trainer
            image: docker.io/sudhan03/algo-trading:ml-prediction-latest
            imagePullPolicy: Always
            command: ["/bin/bash", "-c"]
            args:
              - |
                echo "Starting Weekly Retraining..."
                # 1. Fetch 90 days of data (High Memory Op)
                python3 src/services/ml_prediction/trainer.py --days 90
                # 2. Trigger hot-reload on API pods
                curl -X POST http://ml-prediction/reload-model
            env:
            - name: DB_HOST
              value: "timescaledb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: DB_PASSWORD
            resources:
              requests:
                memory: "4Gi"
                cpu: "2000m"
              limits:
                memory: "8Gi"
                cpu: "4000m"
            volumeMounts:
            - name: model-storage
              mountPath: /app/models
          restartPolicy: OnFailure
          volumes:
          - name: model-storage
            persistentVolumeClaim:
              claimName: trading-pvc
