apiVersion: v1
kind: ServiceAccount
metadata:
  name: dagster
  namespace: trading
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-role
  namespace: trading
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-role-binding
  namespace: trading
subjects:
- kind: ServiceAccount
  name: dagster
  namespace: trading
roleRef:
  kind: Role
  name: dagster-role
  apiGroup: rbac.authorization.k8s.io
