apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: web
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
      
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        editable: true
        jsonData:
          maxLines: 5000

