---
# PersistentVolumeClaim for Dagster compute logs
# Provides shared storage for job logs across all run pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-logs-pvc
  namespace: orchestrator
  labels:
    app: dagster
    app.kubernetes.io/part-of: unified-orchestrator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PersistentVolumeClaim for ML model artifacts
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: orchestrator
  labels:
    app: dagster
    app.kubernetes.io/part-of: unified-orchestrator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
