spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: nginx
        image: docker.io/sudhan03/blog-site:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: blog-nginx-conf