apiVersion: v1
kind: Secret
metadata:
  name: blog-db-secret
  namespace: web
type: Opaque
data:
  # Base64 encoded DATABASE_URL
  # To update: echo -n 'postgresql://blog_user:NEW_PASSWORD@postgres-service:5432/blog_db?sslmode=disable' | base64
  database-url: cG9zdGdyZXNxbDovL2Jsb2dfdXNlcjpaeDltS3A0dk5xOHJMdDJ3WWg1akdmM2NEZTdhWGI2c1F3MXVSZTBvQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9ibG9nX2RiP3NzbG1vZGU9ZGlzYWJsZQ==
